### ISSUE TITLE
stdout redirection

### ISSUE THREAD

**Issue by goto1134** [jnr/jnr-ffi#121]
Is there a way to redirect the output of loaded library?

I'v already tried to use `Variable<Pointer> stdout()` as part of my interface and could not get the value.

**Comment by headius** [comment]
I'm confused by your question. Most libraries that deal with stdio streams will use C globals for them or assume they're at file descriptors 0, 1, and 2. Libraries that provide a way to use alternative streams will usually provide a function to tell them what file descriptor to use.

If a library just uses the C notion of stdout etc, there is no easy way to make that library redirect on its own without affecting all other libraries loaded into the process.

**Comment by goto1134** [comment]
But what is wrong with a Variable method? if it will not be `stdout`, but another global variable the method will work?

**Comment by headius** [comment]
Ahh ok I think you misunderstand something here. "Variable" is a supertype used for several classes of values, like NumberVariable, PointerVariable, and so on. It is not for binding variables in C.

Also note that C does not export variables from libraries, so it's not really possible to introspect this variable from outside the library.

In this case, the only way you'd be able to access or rewrite the `stdout` variable in a C program would be to write a C function that returns the address of that variable, something like:

```c
int* get_stdout()
{
    return &stdout;
}
```

...and then call that via jnr-ffi.

The other option would be for you to redirect stdout for *the whole process* by using the C function `reopen` to replace the `stdout` file descriptor with a redirected one. But that's outside the scope of this issue.

I'm going to close this, since jnr-ffi does not have a way to bind C globals (nor does C make such a thing possible as a dynamic library).

**Comment by nirvdrum** [comment]
I don't know about the original issue here, but the description of `Variable` has me confused. According to the javadocs:

```
Access library global variables.

To access global variables, declare a method with a parameterized return type of this class.
```

And indeed, we use it in jnr-posix to get a [handle to environ](https://github.com/jnr/jnr-posix/blob/e7cec5153a3aea668e7d6b70ab482e1f7fd769f3/src/main/java/jnr/posix/LibC.java#L168). I haven't dug terribly deeply into it, but it looks like jffi will call `dlsym` on the variable name (must be `extern`) to get the address.

**Comment by headius** [comment]
@nirvdrum Oops, you're right...I had forgotten that you can explicitly extern a variable, even though normal non-extern globals aren't exposed.

I think the problem in this case may be that `stdout` is not defined (not available to extern or introspect) by the library in question, since it's provided by e.g. libc, or the kernel, or something else that implements stdio. On my OS X system, it doesn't appear to be externed by libc.dylib...so it would require a bit of hunting.

At any rate, you wouldn't be able to redirect stdout for a single library, unless that library already made its own version of stdout that you could manipulate independent of the rest of the application.

@goto1134 Long story short...you were right in your use of Variable to access externed globals, but in this case it seems stdout is both difficult (or impossible) to find and bind, and unlikely to be tweakable on a per-library basis.

**Comment by goto1134** [comment]
I think, `stdlib` externs the `stdout`, but I tried to get it and `UsatisfiedLinkError` happened.

**Comment by headius** [comment]
Can you confirm that some library you've loaded exposes that global as "stdout"? It's also possible "stdout" gets macro-mangled into some other name on your platform.
