### ISSUE TITLE
BooleanInvoker return incorrect value

### ISSUE THREAD

**Issue by tianxiaogu** [jnr/jnr-ffi#218]
<https://github.com/jnr/jnr-ffi/blob/47ed16fd0d42a3adc9e25be41bfef5dc2953f899/src/main/java/jnr/ffi/provider/jffi/DefaultInvokerFactory.java#L506-L511>

Here perhaps we should first cast `int` to `byte` to remove high bytes and then do zero test.

We are working on a customized FFI library based on JNR. We extended `DefaultInvokerFactory` to support indirect method invocations via function pointers. We then observed that a boolean function returns random values. Since the issue occurs in our code base, we are not sure it is also a bug in the `DefaultInvokerFactory`. Please help me close this issue if it is not a bug. Thanks a lot.

**Comment by headius** [comment]
When would we see a non-zero value that should be treated as false? Do you have an example C library that demonstrates this issue?

Put another way... if you have a library that is returning a value with high bytes that should be ignored, it seems like you should be invoking it as an `int` and masking those bytes yourself.

I would like to see a real-world example before we make any changes here.

**Comment by tianxiaogu** [comment]
The library we used is actually developed in C++. I am not sure whether the issue on our side is a misusage of JNR. Here is an example that can manifest the issue.

```c
long toLong(int i) {
  return 123456789123 + i;
}

extern "C" {

bool testBoolean(int i) {
  toLong(i); // toLong will update value of eax
  return i > 0;
}
}
```

Save the code snippet into a file named `t.cpp` and build the library using the following command:

```
g++ t.cpp -o libbooltest.so -shared -fPIC -O0
```

Dump the library and you will find the result is set by update `%al` only. The result value of `toLong` may fill non-zero bytes to `%eax`.

```
0000000000001138 <testBoolean>:
    1138:	f3 0f 1e fa          	endbr64 
    113c:	55                   	push   %rbp
    113d:	48 89 e5             	mov    %rsp,%rbp
    1140:	48 83 ec 10          	sub    $0x10,%rsp
    1144:	89 7d fc             	mov    %edi,-0x4(%rbp)
    1147:	8b 45 fc             	mov    -0x4(%rbp),%eax
    114a:	89 c7                	mov    %eax,%edi
    114c:	e8 ff fe ff ff       	callq  1050 <_Z6toLongi@plt>
    1151:	83 7d fc 00          	cmpl   $0x0,-0x4(%rbp)
    1155:	0f 9f c0             	setg   %al
    1158:	c9                   	leaveq 
    1159:	c3                   	retq   

```

Now use the following Java code.

```java
import jnr.ffi.LibraryLoader;

public class T {
    public static interface LibBoolTest {
        boolean testBoolean(int i);
    }

    public static void main(String[] args) {
        LibBoolTest boolTest = LibraryLoader.create(LibBoolTest.class).load("booltest");

        for (int i = -1000; i < 1000; i++) {
            if (boolTest.testBoolean(i) != (i > 0)) {
                throw new IllegalStateException("Incorrect value of " + i);
            }
        }
    }
}
```

Build and run the Java program. Remember to disable `AsmLibrary`

```
java -Djava.library.path=<your-library-path> -Djnr.ffi.asm.enabled=false -cp <your-class-path> T
```

gcc version:
```
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```

**Comment by headius** [comment]
Great reproduction, thank you!

So the issue is that the C++ `bool` type is actually narrower than `int`, so propagating a `bool` only populates the lower bytes. As a result, our treating the return value as `int` pulls in high bytes that are unrelated to the boolean value.

I tried to research what happens when a `bool` is exported from C++ to C but have not found much information. Within C++, `bool` values converted to `int` are exactly 1 for true and 0 for false, and this is done explictly by the compiler because it knows what a `bool` is. The problem really is when you attempt to use a `bool` value thinking it is already an `int`.

I don't think it would be appropriate for us to modify BooleanInvoker since it is designed around the C representation of a boolean as being `int` width, and cropping any part of that would be a visible behavior change. It may be possible to make this configurable, so you can specify the width of the relevant part of the value.

A better option might be adding a new type to jnr-ffi to represent a C++ `bool` on the host platform. The width of `bool` is C++ compiler-specific, so we may run into issues there, but it seems like most modern C++ compilers use a single byte.

What do you think?

**Comment by tianxiaogu** [comment]
Thanks a lot for your reply! 

> I don't think it would be appropriate for us to modify BooleanInvoker since it is designed around the C representation of a boolean as being int width, and cropping any part of that would be a visible behavior change.

Yes, I agree with you. There is no need to modify BooleanInvoker. We have a solution on our side since we are working particularly for C++.
