### ISSUE TITLE
JNR-FFI doesn't support for Andoird

### ISSUE THREAD

**Issue by lygstate** [jnr/jnr-ffi#37]

**Comment by headius** [comment]
What's missing? There's ARM support in jffi and jnr-ffi already.

**Comment by atsushieno** [comment]
Android ClassLoader does not support defineClass(). It throws UnsupportedOperationException.
http://tools.oesf.biz/android-6.0.0_r1.0/xref/libcore/libart/src/main/java/java/lang/ClassLoader.java

Because, Android does not use Java bytecode. It must be converted to .dex (and .oat internally) and loaded via DexClassLoader. BridJ and Clojure-Android use it, with some dx internals (I used CfTranslator for Android support in BridJ). asmdex might be usable in 2015, but I haven't tried.

**Comment by headius** [comment]
ARM support has been updated and improved since this issue, and there's always the reflective library binding available if runtime bytecode generation is not available. I think I'm going to close this; if there are still issues getting jnr-* working on Android, please file them as new, distinct issues.

**Comment by lygstate** [comment]
There is no demo for android yet.

**Comment by lygstate** [comment]
For android it's not working at all.

**Comment by kkrishnan90** [comment]
This library doesn't work with Android and seems to fail with `ExceptionInInitializerError`. However, the same .so file called through JNI works absolutely fine. I am pretty sure that I've built my .so files for all arch types/ABIs. Could you please post a documentation on Android too ? I'm a bit eager to understand why it fails. I can also reach out to fix this bug if you are provide me the details on the same. Eagerly waiting for your response !
