### ISSUE TITLE
Possible to use clang block functions?

### ISSUE THREAD

**Issue by srs** [jnr/jnr-ffi#56]
Hi.

This is more a question that an issue. I am trying to use an existing library (xpc) on OSX. This library are using clang code-blocks and one is defined like this:

    typedef void (^xpc_handler_t)( xpc_object_t object);

The function I am trying to call needs to pass a code-block as one of the parameters:

     void xpc_connection_set_event_handler(xpc_connection_t connection, xpc_handler_t handler);

Is this possible, or do I need to start using JNI here?

BR,
Sten Roger

**Comment by headius** [comment]
I believe there's an example of passing Java objects to C as function pointers, either in jnr-ffi or jnr-examples. At any rate, I know it's possible, because Ruby FFI does it (and it uses jnr-ffi when running with JRuby).

Anyway, there's no bug here. Let me know if you can't find the examples. I know we need better doco.
