### ISSUE TITLE
Support explicit packing alignment in structures

### ISSUE THREAD

**Issue by flandr** [jnr/jnr-ffi#8]
Some C libraries use the `pack` compiler pragma to explicitly control alignment of structure fields for ABI compatibility across multiple architectures (e.g. [libkrb5](http://web.mit.edu/kerberos/) on OSX). This causes problems when passing structures across the jnr-ffi boundary to and from native libraries. For example, the structure

    #pragma pack(push, 2)
    struct foo {
        uint32_t value;
        void *pointer;
    };

will have size 12 in native code, but will have 16 if defined thusly in jnr-ffi:

    class Foo extends Struct {
        u_int32_t value = new u_int32_t();
        Pointer pointer = new Pointer();
        // ...
     }

leading to incorrect values for `Foo.pointer.get()`. We can address this by adding a `@Pack` annotation that takes an explicit padding value on a per-structure basis.

**Comment by headius** [comment]
Looks like this slipped through the cracks for some time. Your patch looks interesting...can we discuss it even though we dropped the ball on merging it?

**Comment by henriqueesteves** [comment]
Another option would be to define the pack value in the Struct constructor, because some libraries may set different pack values depending on the platform. The specification PKCS#11 does this (http://www.emc.com/emc-plus/rsa-labs/standards-initiatives/pkcs-11-cryptographic-token-interface-standard.htm), whereas in WIN16 and WIN32 platforms the pack value should be set to 1, in UNIX platforms the pack value may or may not be set to 1 (in the implementations that I know, the pack value used is the default). In this case, if an annotation is used to define the pack value, you must create two  copies of the structures and change only the pack value.

**Comment by flandr** [comment]
My reasoning was that annotations map more closely to pragmas and would simplify mechanical translation between a header and the type definition (and also prevent errors at instantiation), but I'm open to an alternative if you strongly prefer a constructor approach. In either case I'll fix all the whitespace errors & update the patch set; sorry about those.

**Comment by henriqueesteves** [comment]
@flandr I agree with you that the solution using annotations is more closely to pragmas, even this is the solution adopted in the .NET platform. But it would be interesting to have at least the option of setting this value through the constructor to avoid the problem of duplicate structures.

**Comment by flandr** [comment]
Sounds reasonable to me; I'll push an updated patch set when I get some time later today.

**Comment by headius** [comment]
@flandr Circling back to this... are both of your PRs still valid to merge for this?

**Comment by headius** [comment]
With #46 merged, I think this can be closed. Open new issues for remaining gaps in Struct logic.
